### ISSUE TITLE
Rename the Task and give it a friendly name

### ISSUE THREAD

**Issue by TheTalll** [TNG/jgiven-azure-plugin#1]
According to other Azure tasks and their naming conventions, rename the JGiven Task like other tasks:
 - task: PublishPipelineArtifact@1
 - task: publishjgivenreport@0

I would suggest: PublishJGivenReport@0.

And please give it a friendly Name for the UI, i.e. "Publish JGiven Report" or something like this. Currently it looks strange in the task overview ;-)

**Comment by fudler** [comment]
Finally corrected in newest version.
