### ISSUE TITLE
Recursive find of reports in multi-module projects

### ISSUE THREAD

**Issue by TheTalll** [TNG/jgiven-azure-plugin#2]
Giving a jgivenReportPatterns like '**/jgiven-reports/html' and centralPath is Build.SourcesDirectory in a multi-module project, I would expect, that all reports in all submodules  matching that pattern are published, submodules that doesn't match that pattern are skipped.

Currently the task fails, if a submodule is found that doesn't match the pattern.

**Comment by andru47** [comment]
Solved in the initial implementation.
