### ISSUE TITLE
Multi-Job aggregation

### ISSUE THREAD

**Issue by TheTalll** [TNG/jgiven-azure-plugin#4]
If you use the task within a multi-job pipeline und call the task in 2 different jobs the tab is displayed und shows only the test results from the first job, that used the task.

I'm not sure how to solve this, but maybe it is a possibility to get one tab per job where the task is executed (and the tab can be named by a parameter tabName: 'Given Unit Tests" for example or, if no tabName is given, a default "JGiven Job 1" or something like this )

Or all results of all jobs can be aggregated in one tab over all jobs (that would be the preferred solution)

**Comment by andru47** [comment]
Solved in the initial implementation. All the results are aggregated in one tab.
